swagger: '2.0'
info:
  version: v1
  title: Phantombuster API
  description: >
    The Phantombuster API gives you control over your account. It is composed of
    HTTPS endpoints returning JSON data.


    Here’s a short list of what the API allows\:


    - Launch and abort agents

    - Get console output, status, progress and messages from an agent

    - Get real-time console output from an agent

    - Get user, agent and script records

    - Write scripts

    - ...


    We deliberately made the API extremely simple to use. Any developer should
    be able to get responses in a matter of minutes.
host: phantombuster.com
basePath: /api/v1
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  '/agent/{id}':
    get:
      tags:
        - Agent
      description: Get an agent record.
      operationId: getAgentRecord
      parameters:
        - name: id
          in: path
          description: ID of the agent to retrieve.
          required: true
          type: integer
        - name: withScript
          in: query
          description: >-
            If present and not empty, and if the agent has an associated script,
            also return the script record.
          required: false
          type: string
      responses:
        '200':
          description: Success
          schema:
            type: object
            properties:
              status:
                type: string
                example: success
              data:
                type: object
                example:
                  id: 1763
                  name: Nice Agent
                  scriptId: 1902
                  proxy: none
                  proxyAddress: null
                  proxyUsername: null
                  proxyPassword: null
                  disableWebSecurity: false
                  ignoreSslErrors: false
                  loadImages: true
                  launch: manually
                  nbLaunches: 94
                  showDebug: true
                  awsFolder: nVFRid8kvsuPeuCL80DnBg
                  executionTimeLimit: 5
                  fileMgmt: folders
                  fileMgmtMaxFolders: 10
                  lastEndMessage: Execution time limit reached
                  lastEndStatus: error
                  maxParallelExecs: 1
                  userAwsFolder: QwYH17CB0Xj
                  nonce: 123
                  script:
                    id: 1902
                    name: nice_agent.coffee
                    source: phantombuster
                    url: null
                    text: ' ... script contents ... '
                    httpHeaders: null
        default:
          description: Error
          schema:
            $ref: '#/definitions/FailApiResponse'
      security:
        - internalApiKey: []
  '/agent/{id}/launch':
    post:
      tags:
        - Agent
      description: Add an agent to the launch queue.
      operationId: launchAgent
      parameters:
        - name: id
          in: path
          description: ID of the agent to launch.
          required: true
          type: integer
        - name: output
          in: query
          description: |
            This allows you to choose what type of response to receive.

            * `json` - todo
            * `result-object` - todo
            * `first-result-object` - todo
            * `result-object-with-output` - todo
            * `event-stream` - todo
            * `raw` - todo
          required: false
          enum:
            - json
            - result-object
            - first-result-object
            - result-object-with-output
            - event-stream
            - raw
          type: string
        - name: command
          in: query
          description: |
            Command to use when launching the agent (optional).

            * `casperjs` - todo
            * `phantomjs` - todo
            * `node` - todo
          required: false
          type: string
          enum:
            - casperjs
            - phantomjs
            - node
        - name: argument
          in: query
          type: string
          required: false
          description: >-
            JSON argument as a String.The argument can be retrieved with
            buster.argument in the agent’s script.
        - name: saveLaunchOptions
          in: query
          type: string
          required: false
          description: >-
            If present and not empty, `command` and `argument` will be saved as
            the default launch options for the agent.
      responses:
        '200':
          description: Success
          schema:
            type: object
            properties:
              status:
                type: string
                example: success
              message:
                type: string
                example: Agent finished (success)
              data:
                type: object
                example:
                  containerId: 76426
                  executionTime: 17
                  exitCode: 0
                  resultObject:
                    your: data
                    is:
                      here:
                        - 123
                  output: "This is a console output line!\r\nAnd this is another one :)\r\n"
        default:
          description: Error
          schema:
            $ref: '#/definitions/FailApiResponse'
      security:
        - internalApiKey: []
  '/agent/{id}/abort':
    post:
      tags:
        - Agent
      description: Abort all running instances of the agent.
      operationId: abortAgent
      parameters:
        - name: id
          in: path
          description: ID of the agent to stop.
          required: true
          type: integer
      responses:
        '200':
          description: Success
          schema:
            type: object
            properties:
              status:
                type: string
                example: success
              data:
                type: object
                example: null
        default:
          description: Error
          schema:
            $ref: '#/definitions/FailApiResponse'
      security:
        - internalApiKey: []
  '/agent/{id}/output':
    get:
      tags:
        - Agent
      description: >-
        Get data from an agent: console output, status, progress and messages.
        This API endpoint is specifically designed so that it’s easy to get
        incremental data from an agent.
      operationId: outputAgent
      parameters:
        - name: id
          in: path
          description: >-
            ID of the agent from which to retrieve the output, status and
            messages.
          required: true
          type: integer
        - name: mode
          in: query
          description: >
            This allows you to choose what type of response to receive.


            * `track` -  the console output from a particular instance is
            returned, as specified by the containerId parameter.

            * `most-recent` - the most recent instance is selected each time a
            request is made.
          required: false
          enum:
            - track
            - most-recent
          type: string
        - name: containerId
          in: query
          description: ID of the instance from which to get console output.
          required: false
          type: number
        - name: fromMessageId
          in: query
          description: Return the agent’s messages starting from this ID.
          required: false
          type: number
        - name: fromOutputPos
          in: query
          description: Return the agent’s console output starting from this position.
          required: false
          type: number
      responses:
        '200':
          description: Success
          schema:
            type: object
            properties:
              status:
                type: string
                example: success
              data:
                type: object
                example:
                  agentStatus: running
                  containerStatus: running
                  runningContainers: 1
                  queuedContainers: 0
                  containerId: 76427
                  progress:
                    progress: 0.1
                    label: Initializing...
                    runtime: 3
                  messages:
                    - id: 65444
                      date: 1414080820
                      text: Agent started
                      type: normal
                      context:
                        - 'Launch type: manual'
                        - 'Execution time limit: 60s'
                  output: >-
                    * Container a255b8220379 started in directory
                    /home/phantom/agent
                  outputPos: 245
                  resultObject:
                    your: data
                    is:
                      here:
                        - 123
        default:
          description: Error
          schema:
            $ref: '#/definitions/FailApiResponse'
      security:
        - internalApiKey: []
  '/agent/{id}/containers':
    get:
      tags:
        - Agent
      description: >-
        Get a list of ended containers for an agent, ordered by date. Useful for
        listing the last available output logs from an agent.
      operationId: containerAgent
      parameters:
        - name: id
          in: path
          description: ID of the agent from which to retrieve the containers.
          required: true
          type: integer
      responses:
        '200':
          description: Success
          schema:
            type: object
            properties:
              status:
                type: string
                example: success
              data:
                type: object
                example:
                  - id: 195119
                    queueDate: 1427810471
                    launchDate: 1427810471
                    launchType: automatic
                    launchNumber: 476
                    endDate: 1427812088
                    lastEndMessage: Agent finished (error)
                    lastEndStatus: error
                    exitCode: 1
                  - id: 195050
                    queueDate: 1427806874
                    launchDate: 1427806874
                    launchType: automatic
                    launchNumber: 475
                    endDate: 1427810029
                    lastEndMessage: Agent finished (success)
                    lastEndStatus: success
                    exitCode: 0
        default:
          description: Error
          schema:
            $ref: '#/definitions/FailApiResponse'
      security:
        - internalApiKey: []
  '/script/by-id/{mode}/{id}':
    get:
      tags:
        - Script
      description: Get a script record by its ID.
      operationId: getScriptById
      parameters:
        - name: id
          in: path
          description: ID of the script to retrieve.
          required: true
          type: integer
        - name: mode
          in: path
          description: JSON or raw text.
          required: true
          type: string
          enum:
            - json
            - raw
        - name: withoutText
          in: query
          description: >-
            If present and not empty, do not send the script’s contents but only
            its metadata (only in JSON mode).
          required: false
          type: string
      responses:
        '200':
          description: Success
          schema:
            type: object
            properties:
              status:
                type: string
                example: success
              data:
                type: object
                example:
                  id: 1902
                  name: nice_agent.coffee
                  source: phantombuster
                  url: null
                  text: ' ... script contents ... '
                  httpHeaders: null
                  lastSaveDate: 1427806874
                  nonce: 123
        default:
          description: Error
          schema:
            $ref: '#/definitions/FailApiResponse'
      security:
        - internalApiKey: []
  '/script/by-name/{mode}/{name}':
    get:
      tags:
        - Script
      description: Get a script record by its name.
      operationId: getScriptByName
      parameters:
        - name: name
          in: path
          description: 'Name of the script to retrieve, with its extension (.js or .coffee).'
          required: true
          type: string
        - name: mode
          in: path
          description: JSON or raw text.
          required: true
          type: string
          enum:
            - json
            - raw
        - name: withoutText
          in: query
          description: >-
            If present and not empty, do not send the script’s contents but only
            its metadata (only in JSON mode).
          required: false
          type: string
      responses:
        '200':
          description: Success
          schema:
            type: object
            properties:
              status:
                type: string
                example: success
              data:
                type: object
                example:
                  id: 1902
                  name: nice_agent.coffee
                  source: phantombuster
                  url: null
                  text: ' ... script contents ... '
                  httpHeaders: null
                  lastSaveDate: 1427806874
                  nonce: 123
        default:
          description: Error
          schema:
            $ref: '#/definitions/FailApiResponse'
      security:
        - internalApiKey: []
  /scripts:
    get:
      tags:
        - Script
      description: Get the list of all your scripts without text.
      operationId: listScripts
      responses:
        '200':
          description: Success
          schema:
            type: object
            properties:
              status:
                type: string
                example: success
              data:
                type: object
                example:
                  - id: 450
                    name: script1.coffee
                    source: phantombuster
                    url: ''
                    httpHeaders: null
                    lastSaveDate: 1446562593
                    nonce: 12
                  - id: 452
                    name: script2.js
                    source: sdk
                    url: ''
                    httpHeaders: null
                    lastSaveDate: 1446562789
                    nonce: 4
        default:
          description: Error
          schema:
            $ref: '#/definitions/FailApiResponse'
      security:
        - internalApiKey: []
  '/script/delete/{id}':
    delete:
      tags:
        - Script
      description: Delete one of your script.
      operationId: deleteScript
      parameters:
        - name: id
          in: path
          description: ID of the script to delete.
          required: true
          type: integer
      responses:
        '200':
          description: Success
          schema:
            type: object
            properties:
              status:
                type: string
                example: success
              data:
                type: object
                example: null
        default:
          description: Error
          schema:
            $ref: '#/definitions/FailApiResponse'
      security:
        - internalApiKey: []
  '/script/{name}':
    post:
      tags:
        - Script
      description: >-
        Update an existing script or create a new one if it does not exist (in
        this case, the new script ID is returned in the data field).
      operationId: updateScript
      parameters:
        - name: name
          in: path
          description: >-
            Name of the script to update or create, with its extension (.js or
            .coffee).
          required: true
          type: string
        - name: text
          in: query
          description: >-
            Full text contents of the script. This parameter must be in the
            request body in x-www-form-urlencoded format.
          required: true
          type: string
        - name: insertOnly
          in: query
          description: >-
            If present and not empty, make sure that we don’t update an existing
            script (optional). An error will be returned if a script with the
            same name already exists.
          required: false
          type: string
        - name: source
          in: query
          description: >-
            Optional String describing from where the script comes from.
            Reserved sources keywords are phantombuster, web, sdk and bot
            builder. Only 20 alpha-numeric characters (and space) are allowed.
          required: false
          type: string
      responses:
        '200':
          description: Success
          schema:
            type: object
            properties:
              status:
                type: string
                example: success
              data:
                type: number
                example: 345
        default:
          description: Error
          schema:
            $ref: '#/definitions/FailApiResponse'
      security:
        - internalApiKey: []
  /user:
    get:
      tags:
        - User
      description: Get information about your Phantombuster account and your agents.
      operationId: getUser
      responses:
        '200':
          description: Success
          schema:
            type: object
            properties:
              status:
                type: string
                example: success
              data:
                type: object
                example:
                  email: excellent.customer@gmail.com
                  timeLeft: 14087
                  emailsLeft: 100
                  captchasLeft: 10
                  storageLeft: 9991347906
                  databaseLeft: 239222784
                  agents:
                    - id: 1388
                      name: My first agent
                      scriptId: 0
                      lastEndMessage: Agent has no associated script
                      lastEndStatus: launch failed
                      queuedContainers: 2
                      runningContainers: 0
                    - id: 1713
                      name: My second agent
                      scriptId: 2003
                      lastEndMessage: Agent finished with exit code 0
                      lastEndStatus: success
                      queuedContainers: 0
                      runningContainers: 1
                      progress:
                        progress: 0.544
                        label: A progress label
                        runtime: 477
        default:
          description: Error
          schema:
            $ref: '#/definitions/FailApiResponse'
      security:
        - internalApiKey: []
securityDefinitions:
  internalApiKey:
    type: apiKey
    in: header
    name: X-Phantombuster-Key-1
definitions:
  SuccessApiResponse:
    type: object
    properties:
      status:
        type: string
      data:
        type: object
  FailApiResponse:
    type: object
    properties:
      status:
        type: string
      message:
        type: string
  SuccessApiResponseNull:
    type: object
    properties:
      status:
        type: string
      data:
        example: null
  SuccessApiResponseNumber:
    type: object
    properties:
      status:
        type: string
      data:
        type: number
